server:
  port: 8001
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true # Ĭ��false������־����ʾִ�е�sql���
    database: mysql
    hibernate.ddl-auto: update #ָ��Ϊupdate��ÿ��������Ŀ����ṹ�б仯��ʱ��������ֶΣ�������ʱ���½������ָ��create����ÿ��������Ŀ����������ݲ�ɾ�������½�
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl #ָ��jpa���Զ������ɲ��ԣ��շ��Զ�ӳ��Ϊ�»��߸�ʽ
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

